### ISSUE TITLE
Update scheme for generating canonical AM1-BCC charges

### ISSUE THREAD

**Issue by jchodera** [choderalab/gaff2xml#89]
It looks like Christopher Bayly has an updated detailed recipe for generating canonical AM1-BCC charges:
http://docs.eyesopen.com/toolkits/cookbook/python/modeling/am1-bcc.html

We should probably update ours to use this.

**Comment by jchodera** [comment]
This should be updated before we rerun everything!

**Comment by kyleabeauchamp** [comment]
I'm going to postpone this temporarily because I don't want to change too many variables simultaneously.  Once the AMBER file pipeline is working, we can worry about the latest and greatest from OE.

We need to push them to publish this scheme in the literature.  We've had to re-run our calculations three times now because this has been a moving target.

**Comment by jchodera** [comment]
Agreed. Let me set up a chat with Christopher about this.

**Comment by jchodera** [comment]
Discussion request sent to Christopher.  I suggested even an arXiv-citable note would be useful to us.

**Comment by kyleabeauchamp** [comment]
Agreed, I'm happy to use whatever scheme he suggests, but having something citable will definitely be useful.

**Comment by kyleabeauchamp** [comment]
Done
